### ISSUE TITLE
ODPF project structure standard

### ISSUE THREAD

**Issue by mabdh** [odpf/shield#121]
## Summary
ODPF project structure [standard](https://github.com/odpf/handbook/blob/master/go/structure.md) prefer to follow domain-driven structure where each domain is located inside its domain main package inside core package.

Although code in shield is currently tidy enough, there is still a `model` and `structs` package holds all entities and services in `internal/{package}`. With the approach like this, it is more likely for the developers to not separate the concern well in the further development considering there is no restriction when adding a functionality for a domain. This can also lead to more complex spaghetti code that mixed logic between several domains.

We need to follow ODPF project structure standard slowly to have a design restriction so we can be more mindful when developing a new functionalities. I am also hoping this will simplify the code base and increase the readability & predictability.

2 points need to be focused on
 - restructure project 
 - restructure middleware (userid responsibilities)

## Proposed solution

We can divide this into multiple tasks covering two points mentioned above. Some changes needed are (each changes could be in its own PR).

### restructure project 

**Move all domain to `core/{domain}` package**  ⛓️  PR #123 Merged
- Currently it is unclear what are domains in shield, we can start by moving all entities in [model](https://github.com/odpf/shield/blob/main/model/model.go) to each of its own domain
- Moving services in `internal/{package}` to its own domain in `core/{domain}`
- Fatal should only happened in `cmd` level, don't use Fatal inside the service/repository, propagate error to cmd level instead

**Refactor server and store** ⛓️  PR #130 Merged
- Move `store` and `server` inside `internal/server` & `internal/store`
- All initialization should be inside cmd package and dependencies are injected there
- There are also possibilities to have `internal/middleware`, `internal/proxy` and `internal/hook` since it is only being used by server (moving them to `pkg` does make sense as well but there is no point to expose it IMO)
- [structs](https://github.com/odpf/shield/tree/main/structs) and [utils](https://github.com/odpf/shield/tree/main/utils) packages can be refactored to be more readable
- `v1beta1` handler needs to be moved to `internal/api` 
- [resources_config](https://github.com/odpf/shield/tree/main/resources_config) and [rules](https://github.com/odpf/shield/tree/main/rules) config could be just centralized inside `config` package
- Some variables named with `Id` better to rename it to `ID`

**Breakdown postgres store into multiple domain repositories** ⛓️ PR #131 In Progress
- Currently `store/postgres` does not use repository but blob and local has one, therefore `store/postgres` has no separation of domain concern, the store does all responsibilities. We need to separate the responsibility by introducing domain repository and move all functions in `store/postgres` to its own doman repository.
- Add unit test with dockertest

There should ideally no logic changes with the tasks above. There is a remaining focus to restructure the middleware `Middleware restructuring (userid responsibilities)` that can be analyzed post project restructure.

### clean up middleware ⚙️ PR #135 
- Cleaning up how we propagate rules, request body, path params via context in proxy server. Context setter and getter is defined in its domain package e.g. rule is in rule packae, for request body and path params we create a new package in `pkg/httputil`
- Service and handler layer should not directly scanning and consuming header value from grpc metadata. Only grpc interceptor and proxy middleware that should does that and pass the value inside context. Service and handler layer only checking the value passed in context

**Comment by mabdh** [comment]
I saw there are several structs have redundant fields e.g.

```
type Group struct {
	Id             string
	Name           string
	Slug           string
	Organization   Organization
	OrganizationId string `json:"orgId"`
	Metadata       map[string]string
	CreatedAt      time.Time
	UpdatedAt      time.Time
}
```

Why can't we just have 
```
type Group struct {
	Id             string
	Name           string
	Slug           string
	Organization   Organization
	Metadata       map[string]string
	CreatedAt      time.Time
	UpdatedAt      time.Time
}
```
Any reason for this? @krtkvrm @rsbh 
cc @AkarshSatija @niharbansal02

**Comment by krtkvrm** [comment]
with `middleware` in the summary, you mean grpc middleware or proxy middleware?

**Comment by mabdh** [comment]
> with `middleware` in the summary, you mean grpc middleware or proxy middleware?

I think that supposed to be `proxy middleware`. That was proposed by @ravisuhag or @AkarshSatija but I might need to gain more context around that to understand the business use cases better.

**Comment by mabdh** [comment]
> We started with using
> 
> ```
> type Group struct {
>     Organization   Organization
>     .
>     .
> }
> ```
> 
> but then seen realized that whenever group is needed, we also need to have `Organization` and possibly query it. That's why we started moving to using `OrganizationId string` and in plan to remove `Organization Organization`. Same is for other structs as well which have relations

With the case that you mentioned, what is the problem if we just use the `Organization Organization` instead of using `OrganizationId string`? The `OrganizationId` should already be inside the `Organization Organization` right?

**Comment by krtkvrm** [comment]
Yes, but would it make sense to just have OrgId relevant in Organization as other fields are seldom used?

**Comment by mabdh** [comment]
@krtkvrm Just figured out that the relation id `OrgID` -> `several Projects` and `OrgID` in the `Project` is just a (back) reference. I think you are correct, `Organization` struct is not really needed there.

**Comment by mabdh** [comment]
Reopening this as there is one more PR to go

**Comment by krtkvrm** [comment]
@mabdh found a bug #139 that was made during merging of https://github.com/odpf/shield/pull/131. Raising a PR to fix it

**Comment by krtkvrm** [comment]
@mabdh found a bug #149 that was made during merging of #131 . Raising a PR to fix it
