### ISSUE TITLE
Shield server not errored out when starting with no connection to spicedb instance

### ISSUE THREAD

**Issue by mabdh** [odpf/shield#125]
**Describe the bug**
Server is still running fine if spicedb is not running and resources & rule config are 0. But when a call to h2c proxy is executed, there is an error to connect to spicedb.

**To Reproduce**
1. Resource and rules folder should be empty thus making resource_config and rule_config to `0`.
2. Make sure spicedb is not running
3. Run `shield server`
4. Server is running

**Expected behavior**
Server should catch and return error early when spice db is not running during the server initiation even though the resource_config and rule_config are 0. There is a need to do ping/light query check to spicedb when server is initiated.

**Comment by krtkvrm** [comment]
Hey,
I am getting this error when spicedb is not working, can you check if you have something running on port 50051
<img width="1695" alt="image" src="https://user-images.githubusercontent.com/3920286/180427811-d7b073f1-18a7-4cb9-a123-62677da02443.png">

**Comment by mabdh** [comment]
@krtkvrm to reproduce, can you try to remove resource config and rules so both show `0` and restart again?

**Comment by krtkvrm** [comment]
same result
<img width="1709" alt="image" src="https://user-images.githubusercontent.com/3920286/180428973-9fd1e96a-26e1-4679-82e3-d222f5d120b0.png">

**Comment by mabdh** [comment]
@krtkvrm oh yes you are correct, I think I was wrong, I tested it not in `main` branch but in my PR.

Regardless, if there is no spice db. There should be no log like this right?
```
info    Connected to spiceDB: localhost:50051
```
Should throw error earlier

**Comment by mabdh** [comment]
@krtkvrm I have added the spicedb initial check in my [PR](https://github.com/odpf/shield/blob/abb351c4f873b03485d73fd2da8cc9c8f2d9d073/store/spicedb/spicedb.go#L22)
