### ISSUE TITLE
Creating namespace via API with no id will create a row with empty id

### ISSUE THREAD

**Issue by mabdh** [odpf/shield#126]
**Describe the bug**
Creating namespace via API with body contains only `name` (the id was not passed). This will create a row in table namespaces and return response with empty id.

**To Reproduce**
1. 
```
curl --location --request POST 'http://localhost:8000/admin/v1beta1/namespaces' \
--header 'X-Shield-Email: user@odpf.io' \
--header 'Content-Type: application/json' \
--data-raw '{
    "name": "req ns"
}'
```
2. Response got
```
{
    "namespace": {
        "id": "",
        "name": "req ns",
        "createdAt": "2022-07-22T06:02:34.396844Z",
        "updatedAt": "2022-07-22T06:02:34.396844Z"
    }
}
```
3. Row in `namespaces` table
<img width="996" alt="Screen Shot 2022-07-22 at 14 00 12" src="https://user-images.githubusercontent.com/4079709/180382627-4bcb06db-4091-434e-914a-adeae33e59e3.png">

**Expected behavior**
ID in table row should not be empty

**Comment by mabdh** [comment]
This is also happened with `CreateRole`

**Comment by mabdh** [comment]
Some discrepancies between each model

Using ID uuid and autogenerated
 - groups
 - organizations
 - policies
 - projects
 - relations
 - resources
 - users

Using ID varchar with no default value and NULLable
 - actions
 - namespaces
 - roles
  
The latter might raise an issue if we create/update the data via API. We might not need API creation for them since the data should be coming from resource.yml.

**Comment by ravisuhag** [comment]
@mabdh Is this closed in 131?

**Comment by mabdh** [comment]
yes correct @ravisuhag
