### ISSUE TITLE
Unit Tests for Postgres Store Layer

### ISSUE THREAD

**Issue by krtkvrm** [odpf/shield#128]
We should Ideally have a storage layer unit tests, as we have been seeing alot of changes in queries due to optimizations we are carrying out and tests are quick feedback for it

**Comment by mabdh** [comment]
A proposal from me:

We can use `dockertest` for this like we do in `siren` and `compass` https://github.com/odpf/siren/blob/main/internal/store/postgres/postgres_test.go

**Comment by mabdh** [comment]
@krtkvrm let me do this as well in this PR https://github.com/odpf/shield/pull/131
