### ISSUE TITLE
Error in Bootstrapping shield from fresh database

### ISSUE THREAD

**Issue by krtkvrm** [odpf/shield#139]
**Describe the bug**
If starting from fresh postgres, we aren't able to bootstrap the DB and SpiceDB Schema, we get this error:
![image](https://user-images.githubusercontent.com/3920286/182222601-0e507f53-79be-4c4c-9ba2-83cfbac289fb.png)

**Cause**
We aren't passing any NamespaceID while creating any role, thus we are getting.
In #131, this line was removed which was check for `namespace_id` to be empty or not - [internal/store/postgres/role.go#L130](https://github.com/odpf/shield/blob/2c7c4e5481f66a236ec062083cc5d4691da1cea8/internal/store/postgres/role.go#L130)

PG Error:
- ![image](https://user-images.githubusercontent.com/3920286/182222414-1ab8441f-cfb5-4782-9d1d-c6f69e811adc.png)

Debug:
- ![image](https://user-images.githubusercontent.com/3920286/182221941-31a38ff9-e269-41bf-b5f3-cd54029a8f00.png)

**To Reproduce**
1. Start a new PG Instance and run `shield migrate`
2. Try to run `shield serve`

**Expected behavior**
We should be successfully bootstrapping the roles, namespaces, actions and schema

**Comment by mabdh** [comment]
This could also relate to #136
