### ISSUE TITLE
List Groups of a User api throwingError

### ISSUE THREAD

**Issue by krtkvrm** [odpf/shield#145]
List Groups of a User api is giving us 500 Error

```sh
GET /admin/v1beta1/users/682f6492-f6ca-43ec-91ec-48ffad05b38e/groups

{
    "code": 13,
    "message": "internal server error",
    "details": []
}
```

This is due to role_id being made complusary - [internal/store/postgres/group_repository.go#L461](https://github.com/odpf/shield/blob/main/internal/store/postgres/group_repository.go#L461)

```go
	if roleID == "" || userID == "" {
		return nil, group.ErrInvalidID
	}

	query, params, err := dialect.Select(
		goqu.I("g.id").As("id"),
		goqu.I("g.metadata").As("metadata"),
		goqu.I("g.name").As("name"),
		goqu.I("g.slug").As("slug"),
		goqu.I("g.updated_at").As("updated_at"),
		goqu.I("g.created_at").As("created_at"),
		goqu.I("g.org_id").As("org_id"),
	).From(goqu.L("relations r")).
		Join(goqu.L("groups g"), goqu.On(
			goqu.I("g.id").Cast("VARCHAR").
				Eq(goqu.I("r.object_id")),
		)).Where(goqu.Ex{
		"r.object_namespace_id": namespace.DefinitionTeam.ID,
		"subject_namespace_id":  namespace.DefinitionUser.ID,
		"subject_id":            userID,
		"role_id":               roleID,
	}).ToSQL()
```

This is not the behaviour expected as we need to return all the groups  member if role_id was empty

**Comment by krtkvrm** [comment]
@mabdh this was seen from https://github.com/odpf/shield/pull/131

**Comment by mabdh** [comment]
Yes, figured that out today and have fixed [here](https://github.com/odpf/shield/blob/edc00b421b444d66cfd91251e76b1f0ced166e9c/internal/store/postgres/group_repository.go#L478)  in https://github.com/odpf/shield/pull/146

**Comment by mabdh** [comment]
I will create a separate branch/PR for these bugs finding
