### ISSUE TITLE
0.5.0 Tracker

### ISSUE THREAD

**Issue by krtkvrm** [odpf/shield#172]
_This issue will be used to track our progress for v0.5.x_

Goal: Make configuration and permission more flexible and granular

Issues:

1. https://github.com/odpf/shield/issues/169
2. https://github.com/odpf/shield/issues/171
3. ~https://github.com/odpf/shield/issues/173~ _Closed this issue_
4. https://github.com/odpf/shield/issues/174

**Comment by ravisuhag** [comment]
@krtkvrm Instead of tracking it with the issue. Let's create a milestone and add these issues to that milestone. e.g. https://github.com/odpf/guardian/milestones

**Comment by krtkvrm** [comment]
oh TIL, will use milestones and close this issue
