### ISSUE TITLE
Unable to call gRPC endpoint for listing users

### ISSUE THREAD

**Issue by sudo-suhas** [odpf/shield#175]
**Describe the bug**
I am receiving an unexpected error when calling the `ListUsers` endpoint using gRPC.

```
ERROR:
  Code: Internal
  Message: unexpected HTTP status code received from server: 400 (Bad Request); malformed header: missing HTTP content-type
```

The logs on the server indicate a failure to route the request:

```
middleware: failed to match rule	{"path": "/v1beta1/users", "err": "undefined proxy rule"}
```

**To Reproduce**
Call the Shield service with `grpcurl`:

```sh
grpcurl \
  -protoset <(buf build -o - /path/to/proton/odpf/shield/v1beta1/shield.proto) \
  -plaintext shield-server-url:80 \
  odpf.shield.v1beta1.ShieldService/ListUsers
```

**Note:** Skipping the `-protoset` parameter causes the command to hang. On the server, the logs indicate a failure to route the request:
```
middleware: failed to match rule	{"path": "/grpc.reflection.v1alpha.ServerReflection/ServerReflectionInfo", "err": "undefined proxy rule"}
```

**Expected behavior**

The server responds with the list of users.

**Additional context**

This also impacts the Shield extractor and sink (https://github.com/odpf/meteor/pull/408) in odpf/meteor.

**Comment by krtkvrm** [comment]
This is working when using without any proxy
