### ISSUE TITLE
schema migration & revision in ShieldDB for resources

### ISSUE THREAD

**Issue by krtkvrm** [odpf/shield#176]
With respect to changes in principals for Resources, we are supposed to change PG schema which is very fixed with Team and Owner.  We will move to only Owner role for resource and it can be either of principals

Tasks on Resources: 
- Remove owner & team  
- Addition of new principals on owner

**Comment by ravisuhag** [comment]
@krtkvrm is this closed with PR?

**Comment by krtkvrm** [comment]
yes, this should have been closed automatically
closing it now
