### ISSUE TITLE
Role Assignment API for namespaces

### ISSUE THREAD

**Issue by krtkvrm** [odpf/shield#178]
We need APIs on how to assign roles to System & Resource Group Namespaces

Tasks
1. RPC(s) on Proton for Role Assignment  
2. Role creation (creating namespace and principal relation) on SpiceDB  
3. Role creation on ShieldDB  

Acceptance Criteria: User should be able to assign role to any principal, for any namespace

**Comment by krtkvrm** [comment]
Issue was closed automatically, these tasks are remaining: 
- Role creation (creating namespace and principal relation) on SpiceDB
- Role creation on ShieldDB

**Comment by ravisuhag** [comment]
@krtkvrm can this closed now?

**Comment by krtkvrm** [comment]
yes
