### ISSUE TITLE
Authz Check API for System Namespaces

### ISSUE THREAD

**Issue by krtkvrm** [odpf/shield#180]
**Current State**: We only have authz check for Resource Group Namespaces

**Expected State**: We should also have authz check layer for System Namespaces as well

**Comment by krtkvrm** [comment]
proposed schema schema:
```
POST "/admin/v1beta1/check"
{
  "object_id": "oijhkas09-012k-0912o",
  "object_namespace":    "shield/organization"
  "permission": "view",
}
```

**Comment by ravisuhag** [comment]
@krtkvrm can this closed now?

**Comment by krtkvrm** [comment]
yes
